### PR TITLE
 Replaced outdated variable to enable registration (fixes #87)

### LINKED ISSUE #87: Registration are disallowed because of an outdated variable.
In `account.php` the line `} else if ( !$Sitewide_Signups ) {` should be replaced with`} else if ( !$Sitewide['Signups']  ) {`

There is no variable defined as `$Sitewide_Signups` and that is why its always displaying that statement.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9778680-registration-are-disallowed-because-of-an-outdated-variable?utm_campaign=plugin&utm_content=tracker%2F86903&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F86903&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by higagan**
In account.php , the line
} else if ( !$Sitewide_Signups ) {
replaced with
} else if ( !$Sitewide['Signups'] ) {

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Sorry to be _really_ picky, but you seem to have removed a level of indentation from the line. This is important as the else follows one that checks if a member is already logged in. Once that is reverted I'll merge this.

**Comment by lewisgoddard** [comment]
Fixes #87

**Comment by higagan** [comment]
Thanks for pointing it out. I have made the change. Kindly verify.

**Comment by lewisgoddard** [comment]
Excellent! Merged, congratulations on your first pull request _and_ bug closure on Simplet.

**Comment by higagan** [comment]
Thanks a lot!!! :)

**Pull request merged**
